### ISSUE TITLE
Change original source files from ".txt" to ".rego" and address the same in python code as well.

### ISSUE THREAD

**Issue by subhrendu1987** [harendranrs/DatasetOpaRules#4]

**Comment by harendranrs** [comment]
Get-ChildItem -Recurse -Filter *.txt | ForEach-Object {
    $newName = $_.FullName -replace '\.txt$', '.rego'
    Rename-Item $_.FullName $newName
    if (Test-Path $_.Name) {
        git rm --cached $_.Name
    }
    git add $newName
}
